package validate

import (
	"fmt"
	"strings"

	"github.com/zhanyan-Ader1y/Themis/internal/themico/model"
	"github.com/zhanyan-Ader1y/Themis/internal/themico/result"
)

// candidateRelationTypes is the closed set a candidate may declare itself.
// supersedes is generated by governance operations only.
var candidateRelationTypes = map[model.RelationType]struct{}{
	model.RelationDependsOn:    {},
	model.RelationConstrains:   {},
	model.RelationDerivedFrom:  {},
	model.RelationAppliesTo:    {},
	model.RelationChallenges:   {},
	model.RelationCorrects:     {},
	model.RelationRecoversFrom: {},
	model.RelationFollows:      {},
	model.RelationRelatedTo:    {},
}

// checkRelations validates only the relations this revision declares. Traversal,
// multi-hop expansion and cycle analysis are a later plan.
func checkRelations(relations []model.Relation, zone model.Zone, targets map[string]model.RecordPointer, zones map[string]model.Zone) []result.Issue {
	issues := make([]result.Issue, 0)
	for index, relation := range relations {
		path := fmt.Sprintf("relations[%d]", index)
		if _, ok := candidateRelationTypes[relation.Type]; !ok {
			issues = append(issues, issue("relation.type_forbidden", path, "relation type cannot be declared by a candidate"))
			continue
		}
		if !strings.HasPrefix(relation.TargetRecordID, "kr_") || len(relation.TargetRecordID) != len("kr_")+32 {
			issues = append(issues, issue("relation.target_invalid", path, "target record ID is malformed"))
			continue
		}
		pointer, found := targets[relation.TargetRecordID]
		if !found {
			issues = append(issues, issue("relation.target_missing", path, "target record does not exist"))
			continue
		}
		if relation.TargetRecordRevision != "" && relation.TargetRecordRevision != pointer.Revision {
			issues = append(issues, issue("relation.target_missing", path, "target record revision is not current"))
			continue
		}
		if zones[relation.TargetRecordID] != zone && !relation.CrossZone {
			issues = append(issues, issue("relation.cross_zone_not_explicit", path, "cross-zone relation must set cross_zone"))
		}
	}
	return issues
}
